// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: dnsapi/v1/dns.proto
//
package dnsapi.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  DNS service
 *
 *  The DNS service is used to interact with the OpenTaxi DNS server.
 */
public interface DnsServiceClientInterface {
  /**
   *  Add a new domain
   *
   *  Adding a new domain will push the domain to the driver server
   *  compliance blockchain. Other driver servers will then be able
   *  to resolve the domain and make requests to the domain to begin
   *  the compliance process.
   */
  public suspend fun addDomain(request: Dns.AddDomainRequest, headers: Headers = emptyMap()):
      ResponseMessage<Dns.AddDomainResponse>

  /**
   *  Get a domain
   *
   *  This is used to check if a domain is in the OpenTaxi DNS
   */
  public suspend fun getDomain(request: Dns.GetDomainRequest, headers: Headers = emptyMap()):
      ResponseMessage<Dns.GetDomainResponse>

  /**
   *  Remove a domain
   *
   *  This removes a domain from the OpenTaxi DNS
   */
  public suspend fun removeDomain(request: Dns.RemoveDomainRequest, headers: Headers = emptyMap()):
      ResponseMessage<Dns.RemoveDomainResponse>
}
